name: on pull request
on:
  pull_request:
    branches: [ "main" ]
    types: [ opened, synchronize, reopened ]

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-code:
    if: ${{ github.event.pull_request.head.repo.fork == false }}
    name: Build code
    runs-on: self-hosted
    permissions:
      contents: read
    env:
      INCLUDE_SLOW_TESTS: "true"
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: https://sonarcloud.io
      SONAR_ORGANIZATION: pickdate
      SONAR_PROJECT_KEY: pickdate_pickdate-api
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'liberica'
          cache: "gradle"

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
        with:
          validate-wrappers: false

      - name: Test
        run: ./gradlew clean build jacocoTestReport --info --stacktrace

      - name: SonarCloud scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  dependency-submission:
    if: ${{ github.event.pull_request.head.repo.fork == false }}

    runs-on: self-hosted
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'liberica'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
        continue-on-error: true
